//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class a3groupEntities : DbContext
    {
        public a3groupEntities()
            : base("name=a3groupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<A3Group_About> A3Group_About { get; set; }
        public virtual DbSet<A3Group_Blog> A3Group_Blog { get; set; }
        public virtual DbSet<A3Group_Blogs> A3Group_Blogs { get; set; }
        public virtual DbSet<A3Group_Contact> A3Group_Contact { get; set; }
        public virtual DbSet<A3Group_Customer> A3Group_Customer { get; set; }
        public virtual DbSet<A3Group_Differences> A3Group_Differences { get; set; }
        public virtual DbSet<A3Group_Features> A3Group_Features { get; set; }
        public virtual DbSet<A3Group_Information> A3Group_Information { get; set; }
        public virtual DbSet<A3Group_Member> A3Group_Member { get; set; }
        public virtual DbSet<A3Group_Partner> A3Group_Partner { get; set; }
        public virtual DbSet<A3Group_Project> A3Group_Project { get; set; }
        public virtual DbSet<A3Group_Quotes> A3Group_Quotes { get; set; }
        public virtual DbSet<A3Group_Services> A3Group_Services { get; set; }
        public virtual DbSet<A3Group_Sliders> A3Group_Sliders { get; set; }
        public virtual DbSet<A3Group_Team> A3Group_Team { get; set; }
        public virtual DbSet<A3Group_Works> A3Group_Works { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<A3Group_Prices> A3Group_Prices { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<A3Group_PartnerInfo> A3Group_PartnerInfo { get; set; }
    }
}
