//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A3Group_Sliders
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Slogan { get; set; }
        public string Description { get; set; }
        public string Video { get; set; }
    }
}
