//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A3Group_Services
    {
        public int id { get; set; }
        public string MainTitle { get; set; }
        public string MainDescription { get; set; }
        public string SubTitle1 { get; set; }
        public string SubDescription1 { get; set; }
        public string SubTitle2 { get; set; }
        public string SubDescription2 { get; set; }
        public string SubTitle3 { get; set; }
        public string SubDescription3 { get; set; }
        public string SubTitle4 { get; set; }
        public string SubDescription4 { get; set; }
        public string SubTitle5 { get; set; }
        public string SubDescription5 { get; set; }
        public string SubTitle6 { get; set; }
        public string SubDescription6 { get; set; }
    }
}
