//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A3Group_Prices
    {
        public int id { get; set; }
        public string MainTitle { get; set; }
        public string MainDescription { get; set; }
        public string Title1 { get; set; }
        public Nullable<int> Price1 { get; set; }
        public string Description1 { get; set; }
        public string Title2 { get; set; }
        public Nullable<int> Price2 { get; set; }
        public string Description2 { get; set; }
        public string Title3 { get; set; }
        public Nullable<int> Price3 { get; set; }
        public string Description3 { get; set; }
    }
}
