//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A3Group_Prices
    {
        public int id { get; set; }
        public string MainTitle { get; set; }
        public string MainDescription { get; set; }
        public string SubTitle1 { get; set; }
        public string Description1 { get; set; }
        public string SubTitle2 { get; set; }
        public string Description2 { get; set; }
        public string SubTitle3 { get; set; }
        public string Description3 { get; set; }
        public string Prices1 { get; set; }
        public string Prices2 { get; set; }
        public string Prices3 { get; set; }
        public string BoldText { get; set; }
        public string Unit1 { get; set; }
        public string Unit2 { get; set; }
        public string Unit3 { get; set; }
    }
}
