//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace A3Group.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class A3Group_Features
    {
        public int id { get; set; }
        public string MainTitle { get; set; }
        public string MainDescription { get; set; }
        public string SubTitle { get; set; }
        public string SubDescription { get; set; }
        public string Strengths { get; set; }
        public string Image { get; set; }
        public string BoldText { get; set; }
        public string SubBoldText { get; set; }
    }
}
